### ISSUE TITLE
2 quick questions: does it do jsx?  how to add typescript ? 

### ISSUE THREAD

**Issue by ApolloTang** [ambar/rollup-jest#1]
2 quick questions: 

1. does it do jsx?  
2. how to add typescript ? 

Thanks!

**Comment by ambar** [comment]
@ApolloTang you could try [@sucrase/jest-plugin](https://github.com/alangpierce/sucrase/tree/master/integrations/jest-plugin) or [es-jest](https://github.com/ambar/es-jest) (esbuild)
