### ISSUE TITLE
Support Rollup 3

### ISSUE THREAD

**Issue by dutchigor** [ambar/rollup-jest#24]
Hi Ambar!

Loving your plugin, I have been using this for a while to transform my tests successfully. But recently Rollup released version 3. I tried to upgrade but unfortunately rollup-jest fails after the udpate. Are there any plans to update rollup to v3?

**Comment by ambar** [comment]
@dutchigor Released v3.1.0, should work now.

**Comment by dutchigor** [comment]
Yep, that did the trick, all my test cases passed. Thanks!
