### ISSUE TITLE
relies on old version of rollup

### ISSUE THREAD

**Issue by rbenzazon** [ambar/rollup-jest#8]
Hello,

I'm trying to trigger a prepare script of a repo using this package. But NPM doesn't install peer dependencies so I have to do it manually.
The problem here is that a lot of rollup's plugins require version 2.x and rollup-jest requires <=1.x so I can't solve my deps.
Is there anything preventing rollup-jest to accept rollup 2.x? If possible, could you update the dependency ?

Best regards

**Comment by ambar** [comment]
@rbenzazon updated rollup to v2 (5ecfb12)

**Comment by rbenzazon** [comment]
Thanks a lot ! it solved the issue :-)
